# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f616bd86f3a9a86aabf330e73c922a3eeb183e7fe09e55c81cf13dae4e1cb61debece748579649ecd895e81392cd57daac7b909cf06abf39231be6efd7bc633b

test:
  secret_key_base: fbabe0c678631e02e939eb98218154efff2ea4aaa0984d062459d2d6d9ddf5d0816b8ca17e9b8a043a3bc54fb8717279a14a3b1abd1e85ce2453a200b42473a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
